# These are supported funding model platforms

#github: PuneethReddyHC
#community_bridge: online-shopping-system-advanced
#open_collective: PuneethReddyHC
#ko_fi: PuneethReddyHC
#tidelift: npm/babel
#liberapay: PuneethReddyHC
#issuehunt: PuneethReddyHC
#otechie: PuneethReddyHC
#custom: github.com
custom : paypal.me/puneethreddyhc
